development: &default
  adapter: postgis
  schema_search_path: "public,postgis"
  postgis_extension: true
  database: goodtalk_dev
  pool: 5
  encoding: unicode

test: &test
  <<: *default
  database: goodtalk_test

cucumber:
  <<: *test
